### ISSUE TITLE
Multi-part geometries do not themselves provide the array interface

### ISSUE THREAD

**Issue by khelfen** [rl-institut/tracbev#28]
I just did a clean installation with the current `dev` branch and I can't get `tracbev` to work at the moment. The following error is thrown when running `python -m tracbev potential_scenario --mode potential`:

```
$ python -m tracbev potential_scenario --mode potential
Reading TracBEV input data...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kilian/Documents/PythonProjects/tracbev-test/tracbev/__main__.py", line 221, in <module>
    main()
  File "/home/kilian/Documents/PythonProjects/tracbev-test/tracbev/__main__.py", line 209, in main
    data = parse_potential_data(p_args)
  File "/home/kilian/Documents/PythonProjects/tracbev-test/tracbev/__main__.py", line 121, in parse_potential_data
    data_dict = parse_data(args)
  File "/home/kilian/Documents/PythonProjects/tracbev-test/tracbev/__main__.py", line 32, in parse_data
    boundaries = gpd.read_file(pathlib.Path(data_dir, parser.get('data', 'boundaries')))
  File "/home/kilian/Documents/PythonProjects/tracbev-test/d_py38_tracbev_test/lib/python3.8/site-packages/geopandas/io/file.py", line 203, in _read_file
    return GeoDataFrame.from_features(
  File "/home/kilian/Documents/PythonProjects/tracbev-test/d_py38_tracbev_test/lib/python3.8/site-packages/geopandas/geodataframe.py", line 587, in from_features
    return GeoDataFrame(rows, columns=columns, crs=crs)
  File "/home/kilian/Documents/PythonProjects/tracbev-test/d_py38_tracbev_test/lib/python3.8/site-packages/geopandas/geodataframe.py", line 138, in __init__
    self["geometry"] = _ensure_geometry(self["geometry"].values, crs)
  File "/home/kilian/Documents/PythonProjects/tracbev-test/d_py38_tracbev_test/lib/python3.8/site-packages/geopandas/geodataframe.py", line 43, in _ensure_geometry
    out = from_shapely(data, crs=crs)
  File "/home/kilian/Documents/PythonProjects/tracbev-test/d_py38_tracbev_test/lib/python3.8/site-packages/geopandas/array.py", line 168, in from_shapely
    return GeometryArray(vectorized.from_shapely(data), crs=crs)
  File "/home/kilian/Documents/PythonProjects/tracbev-test/d_py38_tracbev_test/lib/python3.8/site-packages/geopandas/_vectorized.py", line 142, in from_shapely
    aout[:] = out
  File "/home/kilian/Documents/PythonProjects/tracbev-test/d_py38_tracbev_test/lib/python3.8/site-packages/shapely/geometry/base.py", line 854, in __array_interface__
    raise NotImplementedError("Multi-part geometries do not themselves "
NotImplementedError: Multi-part geometries do not themselves provide the array interface
```

**Comment by mosc5** [comment]
Clean pip install leads to the same error on my machine (linux).
Testing solutions:

- [x] Use input data from working installation
- [ ] gradually update env to reflect working installation
- [ ] use new input data

Geopandas code snippet from non-working version: (_vectorized.py, line 140-142)
`aout = np.empty(len(data), dtype=object)
        with compat.ignore_shapely2_warnings():
            aout[:] = out`

Older working geopandas version does not contain line "with compat. ..."

This is where the error gets raised

**Comment by nailend** [comment]
I had the same error using `ding0`. Having installed the following packages. Maybe this is of help;
```
attrs==22.1.0
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
click==8.1.3
click-plugins==1.1.1
cligj==0.7.2
cryptography==37.0.4
cycler==0.11.0
decorator==4.4.2
descartes==1.1.0
ding0==0.2.1
egoio==0.4.8
Fiona==1.8.21
GeoAlchemy2==0.6.3
geographiclib==1.52
geopandas==0.9.0
geopy==2.1.0
idna==3.3
importlib-metadata==4.12.0
jeepney==0.8.0
keyring==23.8.2
keyrings.alt==4.1.1
kiwisolver==1.4.4
linecache2==1.0.0
matplotlib==3.4.2
munch==2.5.0
networkx==2.5.1
numexpr==2.8.3
numpy==1.23.1
oedialect==0.0.10
packaging==21.3
pandas==1.2.4
Pillow==9.2.0
ply==3.11
psycopg2-binary==2.9.3
pycparser==2.21
Pyomo==6.4.1
pyparsing==3.0.9
pyproj==3.0.1
pypsa==0.17.1
python-dateutil==2.8.2
pytz==2022.1
requests==2.28.1
scipy==1.9.0
seaborn==0.11.1
SecretStorage==3.3.2
Shapely==1.7.1
six==1.16.0
SQLAlchemy==1.3.24
tables==3.7.0
traceback2==1.4.0
unittest2==1.1.0
urllib3==1.26.11
zipp==3.8.1
```
